### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by alver** [cavenel/ev3-print3rbot#10]
Good day.

Tried to repeat your work, but looks like it impossible to do now. If I complete instruction in this project - i've got an error:
Traceback (most recent call last):
  File "./writer.py", line 484, in <module>
    main()
  File "./writer.py", line 475, in main
    wri = Writer(calibrate = True)
  File "./writer.py", line 73, in **init**
    self.touch_A  = TouchSensor(INPUT_3)
  File "build/bdist.linux-armv5tejl/egg/ev3dev/core.py", line 1664, in **init**
  File "build/bdist.linux-armv5tejl/egg/ev3dev/core.py", line 180, in **init**
  File "build/bdist.linux-armv5tejl/egg/ev3dev/core.py", line 123, in list_device_names
OSError: [Errno 2] No such file or directory: '/sys/class/lego-sensor'

I checked this link - https://github.com/ddemidov/ev3dev-lang-python - looks like this version doesn't support python2 anymore. Are you planning to refresh your instruction and code to make it able to work in current ev3dev environment?

**Comment by cavenel** [comment]
Sorry, a lot has changed on the ev3dev firmware for motors these last months (by @rhempel), and I didn't have time to follow. I won't have time soon to update the code, but any help on that is welcome! Only a few lines are responsible for the motor interaction, so it shouldn't be a lot of work if you know a bit of Python!

**Comment by alver** [comment]
Sure, np. Trying to fix this now.
For now i stuck with "speed_regulation_enabled", they remove this flag totally. Need time to understand previous API and current one

**Comment by alver** [comment]
Ok, it's work for me now. Created a PR, up to you what do to with it :)

**Comment by cavenel** [comment]
Awesome thank you! PR merged.

**Comment by alver** [comment]
Thank you, this is incredible project, i like it a lot.
