### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by hakanatas** [cavenel/ev3-print3rbot#12]
Hi ,
when i write terminal "python writer.py " it gives me error "SystemError: Must be using Python 3.4 or higher"

and i write on terminal "python3 writer.py" it gives me "Mising parantheses in call" error. 

is this related to  https://github.com/ddemidov/ev3dev-lang-python because in that link "This version of python bindings has been deprecated!" and i followed the link. 

how can i fix the problem? any idea?

**Comment by cavenel** [comment]
Hi,

Unfortunately, this project has big trouble following ev3dev's updates. Apparently ev3dev now only comes with Python3, and the code here is for Python 2.7. It will need some rewriting to be up to date, which I won't be able to do now.
Someone updated the code some weeks ago but the frequency of breaking updates from ev3dev is too high to maintain working code.

Sorry again, the only solution right now is to change the code to follow Python 3 syntax, especially with print :
Python 2.7:

```
print "ok"
```

Python 3:

```
print ("ok") 
```

**Comment by cavenel** [comment]
The code has been updated to fix the parentheses problem with Python3. Please let me know if there is any other problem by opening another issue.
