### ISSUE TITLE
What is tacho-motor?

### ISSUE THREAD

**Issue by Whatisthis8047** [cavenel/ev3-print3rbot#14]
File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 634, in stop_action
    self._stop_action = self.set_attr_string(self._stop_action, 'stop_action', value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 219, in set_attr_string
    return self._set_attribute(attribute, name, value)
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 199, in _set_attribute
    attribute = self._attribute_file_open( name )
  File "/usr/lib/python3/dist-packages/ev3dev/core.py", line 171, in _attribute_file_open
    mode = stat.S_IMODE(os.stat(path)[stat.ST_MODE])
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/tacho-motor/motor1/stop_action

I got this error again.. I thought is was a system error so I've reflashed new image file but it came up again. I've got into /sys/class/tacho-motor/motor1/ folder but I couldn't find file "stop_action" what is tacho-motor exactly? what should I do to run writer.py?? I really want to run this robot :'(

**Comment by cavenel** [comment]
Hi,

Tacho-motor is the class of all Lego motors. If your motor is a standard Lego motor (large or medium) you should have the attribute "stop_action" in /sys/class/tacho-motor/motor1/

Can you give me the name of the image file you flashed? I checked with the last version and I do have "stop_action" both for the medium and the large motor in /sys/class/tacho-motor/motor*/

**Comment by cavenel** [comment]
Just rebuilt the print3rbot and checked, everything is working fine with python3. I will close this issue, don't hesitate to reopen if you still have the problem.

**Comment by Whatisthis8047** [comment]
Thanks for the comment, I've solved it! The kernel version was the problem. I'm not sure why but the original kernel which is built in image file doesn't have "stop_action".
