### ISSUE TITLE
Custom Image

### ISSUE THREAD

**Issue by SchoolUser** [cavenel/ev3-print3rbot#2]
I may be missing something, but I am wondering how to put a custom image on the robot. I have tried everything I could think of and I cannot find any way to do it.

**Comment by cavenel** [comment]
Hi,

First I am really happy that you manage to build the robot and make it work. I would love to have some feedbacks!

For your issue, I would like to know what you try.
Here are the steps I follow:
1. Create an image with Inkscape (using only simple paths if possible. Can be texts or complex shapes as well if you convert it after).
2. Convert your image to paths (see [documentation](https://github.com/cavenel/ev3-print3rbot#drawing-an-svg-image))
3. Save your image in the robot (via ssh or any other method to access the EV3 filesystem, see ev3dev documentation). For example, if the python file is in /home/user, you can save in /home/user/images/myimage.svg
4. Change line 476 of writer.py to:

``` Python
wri.draw_image(image_file = 'images/myimage.svg',max_speed=50)

But let me know if it works and, if not, what you tried!
```

**Comment by SchoolUser** [comment]
Sorry, but I am new to Python, so I was wondering if you could tell me how to use ssh to save the image on the robot, I am using putty if that is of any help

**Comment by cavenel** [comment]
You should have a look at [WinSCP](http://winscp.net/). You can use the same ssh settings as in Putty, and you will be able to transfer files from windows to the ev3.

**Comment by SchoolUser** [comment]
I have all the source libraries installed, yet it says that writer.py is not an executable file unless I am not understanding this

**Comment by cavenel** [comment]
To execute Python, you can use:

```
python writer.py
```

or make the file executable before launching it:

```
chmod +x writer.py
./writer.py
```

**Comment by SchoolUser** [comment]
![img_1136](https://cloud.githubusercontent.com/assets/12626286/7912991/143ead04-083a-11e5-87b9-f78da947bf7e.JPG)
We got it to work, but it won't draw because the gear is not touching the corkscrew, do you have any suggestion?

**Comment by cavenel** [comment]
Hi,

It looks like you inverted the two yellow pieces with the grey corkscrew. The yellow pieces should touch the motor. Then there should be contact!
Awesome if everything else works! Let me know how it goes.

**Comment by SchoolUser** [comment]
Sorry about that, we are working as a group, so I did not assemble it, and do not know what it is supposed to look like

**Comment by cavenel** [comment]
No problem. I will close this issue, as the "custom image" problem is solved. Please open a new issue if you have any more problems! :)
