### ISSUE TITLE
Is the second touch sensor a must...? 

### ISSUE THREAD

**Issue by skampala1** [cavenel/ev3-print3rbot#6]
@cavenel  I got no second touch sensor....is there any way it can work properly without the second touch sensor..? Please help me out...!

**Comment by cavenel** [comment]
As seen somewhere else, here could be one solution:
- remove te touch sensor from the robot. It is better to use zero than one touch sensor.
- replace the file writer.py with this one: https://www.dropbox.com/s/ot17lg25t8dcars/writer.py?dl=1 (removes the calibration of arm motors)
- put both arms in maximum open position (this will do the calibration manually).
- launch writer.py

**Comment by skampala1** [comment]
When I launch writer.py, I get this error:
root@ev3dev:~/ev3-print3rbot# chmod +x writer.py
root@ev3dev:~/ev3-print3rbot# ./writer.py
Traceback (most recent call last):
  File "./writer.py", line 484, in <module>
    main()
  File "./writer.py", line 475, in main
    wri = Writer(calibrate = True)
  File "./writer.py", line 77, in **init**
    self.calibrate()
  File "./writer.py", line 107, in calibrate
    if (self.touch_A.value()):
RuntimeError: no device connected: Function not implemented

**Comment by wuyanrobert** [comment]
hello
i can't understand what we use the touch sensor for ？
can you explain how it works please?

**Comment by cavenel** [comment]
The touch sensors are for calibration of the drawing arms.
