### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by melonhead2** [cavenel/ev3-print3rbot#8]
Can you update the code so that I can work with the new bindings of rhempel/ev3dev-lang-python?

Thanks!

**Comment by cavenel** [comment]
Hi!

Unfortunately I don't have the robot with me right now.
But it should be quite easy to update the code as you only need to update mymotor class.
I will have a look on that in about one week!

**Comment by melonhead2** [comment]
Hello,

I am using this for a school project, and the deadline is approaching. Do you have a rough estimate for how long it will take for you to complete it? Thanks so much for helping me out @cavenel!

**Comment by cavenel** [comment]
Closed as code has been updated for now thanks to @iWildStyle.
